# Generated by Django 6.0.2 on 2026-04-27 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfgen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='report',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='reports/'),
        ),
    ]
