version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: django_app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery_worker
    command: celery -A school worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery_beat
    command: celery -A school beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis